app:
    resource: "@AppBundle/Controller/"
    type:     annotation

advert:
    resource: "@AppBundle/Controller/AdvertController.php"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
